### ISSUE TITLE
Implement PollyCache using a action filter

### ISSUE THREAD

**Issue by umeshkarthik** [App-vNext/Polly.Caching.MemoryCache#27] opened 2018-10-23 20:28 UTC
I have been trying to implement PolyCAche for my controller action method as a action filter which basically uses the in-memory caching mechanism

**Comment by reisenberger** [comment] 2018-10-25 07:01
Duplicate of https://github.com/App-vNext/Polly/issues/521

**Closed by reisenberger** 2018-10-25 07:01 UTC
