### ISSUE TITLE
Reference conflicts.

### ISSUE THREAD

**Issue by marcelmunarolo** [App-vNext/Polly.Caching.MemoryCache#23] opened 2018-06-13 13:33 UTC
Dear colleagues,

I am trying to configure this package (Polly.Caching.MemoryCache v1.1.0) together with the Polly version 6.0.1, using an ASP.NET Core 2.1 project. After create a MemoryCacheProvider, I can't use it in a Policy.CacheAsync method, receiving the following message at the compile time:

Error CS0012 The type 'IAsyncCacheProvider' is defined in an assembly that is not referenced. You must add a reference to assembly 'Polly, Version=5.9.0.0, Culture=neutral, PublicKeyToken=null'

The code:
            IMemoryCache memoryCache = new MemoryCache(new MemoryCacheOptions());
            var memoryCacheProvider = new MemoryCacheProvider(memoryCache);
            var cachePolicy = Policy.CacheAsync(memoryCacheProvider, TimeSpan.FromSeconds(5));

Is there any way to use this package with the Polly's last version?
Thank you very much!

**Comment by andreujuanc** [comment] 2018-06-13 22:46
I got the samething. Prob caused by this library not using netstandard2.0 . Will try building source and see.

**Comment by Pvlerick** [comment] 2018-06-14 11:11
Stuck in the same way, waiting for this PR to go through :-)

**Comment by andreujuanc** [comment] 2018-06-14 12:06
1) Cloned the repo, changed to v20dev branch, 
2) dotnet2.1 folder, dotnet build
3) ????
4) PROFIT

Jokes aside. temporaly local reference to the dll, or even just refenrence the project, while the PR,nuget, etc comes live. 

Maybe it hasnt passed all the tests, idk xD but i love to live in the edge..

**Comment by Pvlerick** [comment] 2018-06-14 13:49
1. Clone, checkout v20dev
2. dotnet build
3. Error: you are behind a corporate proxy
4. Wait

I'll try to find a workaround while waiting :-)

**Comment by joelhulen** [comment] 2018-06-14 16:59
I just merged the PR. I don't know why I didn't get a notification. Posting the NuGet package shortly.

**Comment by joelhulen** [comment] 2018-06-14 17:19
By the way, the package has changed names. Please refer to this NuGet package from now on: [https://www.nuget.org/packages/Polly.Caching.Memory](https://www.nuget.org/packages/Polly.Caching.Memory)

**Comment by reisenberger** [comment] 2018-06-15 06:38
Closed by #22

**Closed by reisenberger** 2018-06-15 06:38 UTC
